config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations'}
  devise_for :freelancers, :employers, :skip => :sessions

  resources :employers
  resources :freelancers
  resources :jobs
  resources :favorites, only: [:create, :destroy]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  root 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base

  validates_presence_of :title, :start_date, :offered_pay_rate, :job_description
  belongs_to :employer, dependent: :destroy
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authenticate_user!

  def index
    @jobs = Job.all.paginate(page: params[:page], per_page: 25)
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(job_params)
      redirect_to @job
    else
      render 'edit'
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to @job
    else
      render 'new'
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

  private

  def job_params
    params.require( :job ).permit(:title, :start_date, :job_description, :offered_pay_rate )
  end

end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>

  <%= f.label :title %><br />
  <%= f.text_field :title %><br />

  <%= f.label :start_date %><br />
  <%= f.date_field :start_date %><br />

  <%= f.label :job_description %><br />
  <%= f.text_area :job_description %><br />

  <%= f.label :offered_pay_rate %><br />
  <%= f.text_field :offered_pay_rate %><br />

  <%= f.submit (@job.new_record? ? "Create" : "Update") %>

<% end %>

app/views/jobs/_jobs.html.erb
<% @jobs.each do |job| %>

    <p><%= link_to job.title, job_path(job.id) %></p>
    <p><%= job.created_at %></p>

<% end %>

app/views/jobs/_search.html.erb
<%= form_tag '/freelancers', :method => "get", id: "search-form", class: "input-group" do %>
<%= search_field_tag :search, params[:search], placeholder: "insert a search query here", class: "form-control", autofocus: true %>
<span class="input-group-btn">
<%= submit_tag "search", :name => nil, id: "search-form", class: "btn btn-secondary" %>
</span>
<% end %>

app/views/jobs/index.html.erb
<% if user_signed_in? && current_user.type === 'Freelancer'%>

<%= render 'search' %>

<% end %>

<%= render 'jobs' %>

<%= will_paginate %>

<% if user_signed_in? && current_user.type === 'Employer'%>

<%= link_to 'create job', new_job_path %>

<% end %>

app/views/jobs/new.html.erb
<%= render 'form' %>

app/views/jobs/show.html.erb
<h2>Job</h2>