config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations'}
  devise_for :freelancers, :employers, :skip => :sessions

  resources :employers
  resources :freelancers
  resources :jobs
  resources :favorites, only: [:create, :destroy]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  root 'jobs#index'

end

app/models/freelancer.rb
class Freelancer < User

  scope :availability, -> (availability) { where availability: availability }
  scope :business, -> (business) { where business: business }
  scope :field, -> (field) { where field: field }
  scope :education, -> (education) { where education: education }

  include Filterable

  validates_presence_of :gender, :education, :field, :availability, :pay_rate, on: :update
  validates :availability, inclusion: { in: %w(Available Unavailable Soon),
    message: "%{value} is not a valid availability type"}, on: :update
  validates :gender, inclusion: { in: %w(Male Female Undefined),
    message: "%{value} is not a valid gender" }, on: :update
  validates :education, inclusion: { in: %w(LBO MBO HBO Academic),
    message: "%{value} is not a valid education"}, on: :update

  def self.search(query)
    where("last_name ILIKE ? OR business ILIKE ? OR field ILIKE ? ", "%#{query}%", "%#{query}%", "%#{query}%")
  end
  
end

app/controllers/freelancers_controller.rb
class FreelancersController < ApplicationController

  before_action :authenticate_user!

  def index
    if params[:search]
      @freelancers = Freelancer.search(params[:search]).order("created_at DESC")
    else
      @freelancers = Freelancer.all.order('created_at DESC')
    end
    @freelancers = Freelancer.filter(params.slice(:availability, :business, :field, :education)).paginate(page: params[:page], per_page: 25)
  end

  def show
    @freelancer = Freelancer.find(params[:id])
  end

  def edit
    @freelancer = Freelancer.find(params[:id])
  end

  def update
    @freelancer = Freelancer.find(params[:id])
    if @freelancer.update_attributes(freelancer_params)
      redirect_to @freelancer
    else
      render 'edit'
    end
  end

  def destroy
    @freelancer = Freelancer.find(params[:id])
    @freelancer.destroy
    redirect_to freelancers_path
  end

end

app/views/freelancers/_search.html.erb
<%= form_tag '/freelancers', :method => "get", id: "search-form", class: "input-group" do %>
<%= search_field_tag :search, params[:search], placeholder: "insert a search query here", autofocus: true, class: "form-control" %>
<span class="input-group-btn">
<%= submit_tag "search", :name => nil, id: "search-form", class: "btn btn-secondary" %>
</span>
<% end %>

app/views/freelancers/index.html.erb
<h2>Freelancers</h2>

<%= render 'search' %>

<%= link_to "Available", freelancers_path(availability: "Available"), class:"btn btn-default" %>
<%= link_to "Just my business", freelancers_path(business: current_user.business ), class:"btn btn-default" %>

<% @freelancers.each do |freelancer| %>
        <p><%= link_to freelancer.first_name, freelancer_path(freelancer.id) %></p>
        <p><%= freelancer.business %></p>
        <p><%= freelancer.field %></p>
        <p><%= freelancer.availability %></p>
<% end %>

<%= will_paginate %>

app/views/freelancers/show.html.erb
<h2><%= @freelancer.first_name %> <%= @freelancer.last_name %></h2>

<p><%= @freelancer.location %></p>
<p><%= @freelancer.business %></p>
<p><%= @freelancer.field %></p>
<p><%= @freelancer.education %></p>
<p><%= @freelancer.availability %></p>
<p><%= @freelancer.pay_rate %></p>

<p><%= @freelancer.description %></p>