config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations'}
  devise_for :freelancers, :employers, :skip => :sessions

  resources :employers
  resources :freelancers
  resources :jobs
  resources :favorites, only: [:create, :destroy]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  root 'jobs#index'

end

app/views/layouts/_account.html.erb
<ul>
    <% if user_signed_in? %>

    <li>
      <%= link_to conversations_path do %>
      <p>
        <i class="fa fa-envelope text-center" aria-hidden="true"></i>
        messages
      </p>
      <% end %>
    </li>

    <li>
      <%= link_to edit_user_registration_path do %>
      <p>
        <i class="fa fa-user text-center" aria-hidden="true"></i>
      account
      </p>
      <% end %>
    </li>

    <% else %>

    <li>
      <%= link_to new_user_session_path do %>
        <p>
          <i class="fa fa-sign-in text-center" aria-hidden="true"></i>
        login
        </p>
      <% end %>
    </li>

    <li>
      <%= link_to new_user_registration_path do %>
        <p>
          <i class="fa fa-user" aria-hidden="true"></i>
        register
        </p>
      <% end %>
    </li>

    <% end %>

    <% if user_signed_in? %>

      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
        <p>
          <i class="fa fa-times text-center" aria-hidden="true"></i>
        log-out
        </p>
        <% end %>
      </li>

    <% end %>
</ul>

app/views/layouts/_flashes.html.erb
<div class="flash-messages">
  <% flash.each do |key, value| %>
  <div class="row">
    <div class="col-xs-12 alert alert-<%= key %>">
      <%= value %>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <h4>Why</h4>
        <p>
          There are lots of recruitment agencies
          around. Most of their work can be done by a spam-bot. Why pay for
          someone who treats your resume like a harlot?

          You don't need a recruiter and you don't need a spam-bot.
        </p>


      </div>
      <div class="col-xs-6 col-sm-3">
        <h4>Settings</h4>
        <ul>
          <li><a href="#!">Link 1</a></li>
          <li><a href="#!">Link 2</a></li>
          <li><a href="#!">Link 3</a></li>
          <li><a href="#!">Link 4</a></li>
        </ul>
      </div>
      <div class="col-xs-6 col-sm-3">
        <h4>Connect</h4>
        <ul>
          <li><a href="#!">Link 1</a></li>
          <li><a href="#!">Link 2</a></li>
          <li><a href="#!">Link 3</a></li>
          <li><a href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          Made by <a href="#">Roggers</a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="site-header size-lg text-center" style="background-image: url(assets/img/bg-banner1.jpg)">
  <div class="container">
    <div class="col-xs-12">

      <h2>Hey, freelancer!<mark>GRAB</mark> your project!</h2>
      <h5 class="font-alt">Before someone else does.</h5>

    </div>

  </div>
</header>

app/views/layouts/_navigation.html.erb
<nav class="navbar">
  <div class="container">

    <!-- Logo -->
    <div class="pull-left">
      <a class="navbar-toggle" href="#" data-toggle="offcanvas"><i class="ti-menu"></i></a>



    </div>
    <!-- END Logo -->

    <!-- User account -->
    <div class="pull-right user-login">
      <%= link_to 'Log in', new_user_session_path, class: 'btn btn-sm btn-primary' %>or <%= link_to 'Register', new_user_registration_path, class: 'btn btn-sm btn-primary' %>
    </div>
    <!-- END User account -->

    <!-- Navigation menu -->
    <ul class="nav-menu">
      <li>
        <a class="active" href="index.html">Home</a>
        <ul>
          <li><a class="active" href="index.html">Version 1</a></li>
          <li><a href="index-2.html">Version 2</a></li>
        </ul>
      </li>
      <li>
        <a href="#">Position</a>
        <ul>
          <li><a href="job-list-1.html">Browse jobs - 1</a></li>
          <li><a href="job-list-2.html">Browse jobs - 2</a></li>
          <li><a href="job-list-3.html">Browse jobs - 3</a></li>
          <li><a href="job-detail.html">Job detail</a></li>
          <li><a href="job-apply.html">Apply for job</a></li>
          <li><a href="job-add.html">Post a job</a></li>
          <li><a href="job-manage.html">Manage jobs</a></li>
          <li><a href="job-candidates.html">Candidates</a></li>
        </ul>
      </li>
      <li>
        <a href="#">Resume</a>
        <ul>
          <li><a href="resume-list.html">Browse resumes</a></li>
          <li><a href="resume-detail.html">Resume detail</a></li>
          <li><a href="resume-add.html">Create a resume</a></li>
          <li><a href="resume-manage.html">Manage resumes</a></li>
        </ul>
      </li>
      <li>
        <a href="#">Company</a>
        <ul>
          <li><a href="company-list.html">Browse companies</a></li>
          <li><a href="company-detail.html">Company detail</a></li>
          <li><a href="company-add.html">Create a company</a></li>
          <li><a href="company-manage.html">Manage companies</a></li>
        </ul>
      </li>
      <li>
        <a href="#">Pages</a>
        <ul>
          <li><a href="page-blog.html">Blog</a></li>
          <li><a href="page-post.html">Blog-post</a></li>
          <li><a href="page-about.html">About</a></li>
          <li><a href="page-contact.html">Contact</a></li>
          <li><a href="page-faq.html">FAQ</a></li>
          <li><a href="page-pricing.html">Pricing</a></li>
          <li><a href="page-typography.html">Typography</a></li>
          <li><a href="page-ui-elements.html">UI elements</a></li>
        </ul>
      </li>
    </ul>
    <!-- END Navigation menu -->
  </div>
</nav>








<!--


<ul>
  <% if user_signed_in? %>

    <li>
      <%= link_to conversations_path do %>
      <p>
        <i class="fa fa-envelope text-center" aria-hidden="true"></i>
        messages
      </p>
      <% end %>
    </li>

    <li><%= link_to edit_user_registration_path do %>
      <p>
        <i class="fa fa-user text-center" aria-hidden="true"></i>
      account
      </p>
      <% end %>
    </li>

    <% else %>

    <li>
      <%= link_to new_user_session_path do %>
      <p>
        <i class="fa fa-sign-in text-center" aria-hidden="true"></i>
      login
      </p>
      <% end %>
    </li>

    <li>
      <%= link_to new_user_registration_path do %>
      <p>
        <i class="fa fa-user" aria-hidden="true"></i>
      register
      </p>
      <% end %>
    </li>

  <% end %>

  <% if user_signed_in? %>
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <p>
        <i class="fa fa-times text-center" aria-hidden="true"></i>
      log-out
      </p>
      <% end %>
    </li>

  <% end %>



  <% if user_signed_in? && current_user.type === 'Freelancer'%>
    <li>
      <%= link_to employers_path do %>
      <p>
        <i class="fa fa-building-o text-center" aria-hidden="true"></i>
        employers
      </p>
      <% end %>
    </li>

    <li>
      <%= link_to jobs_path do %>
      <p>
        <i class="fa fa-briefcase text-center" aria-hidden="true"></i>
        jobs
      </p>
      <% end %>
    </li>
  <% end %>



  <% if user_signed_in? && current_user.type === 'Employer'%>
    <li>
      <%= link_to freelancers_path do %>
      <p>
        <i class="fa fa-building-o text-center" aria-hidden="true"></i>
        freelancers
      </p>
      <% end %>
    </li>
  <% end %>
</ul> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interimagenda</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/navigation" %>

  <%= render "layouts/flashes" %>

  <% if !current_user %>

  <%= render "layouts/header" %>

  <% end %>

<%= yield %>

</body>
</html>

app/views/layouts/header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><a href="#">Link</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>